import './excercices/1480.sum-of-1d-array.ts';
import './excercices/724.find-pivot-index.ts';
import './excercices/392.is-subsequence.ts';
import './excercices/205.isomorphic-strings.ts';
import './excercices/206.reverse-linked-list.ts';
import './excercices/876.middle-of-linked-list.ts';
import './excercices/142.linked-list-cycle-2.ts';
import './excercices/121.best-time-to-buy-and-sell-stock.ts';
import './excercices/409.longest-palindrome.ts';
import './excercices/589.n-ary-preorder-traversal.ts'
import './excercices/102.binary-tree-level-order-traversal.ts'
import './excercices/704.binary-search.ts';
import './excercices/278.first-bad-version.ts';
import './excercices/98.validate-binary-search-tree.ts';
import './excercices/235.lowest-common-ancestor.ts';
import './excercices/733.flood-fill.ts';
